### PR TITLE
Added example files and updated manual

### PR DESCRIPTION
**Pull request by qiyunzhu**
I added some example files. I have confirmed with Greg that the information in this file are not confidential. And I modified it little bit. This PR is not dependent on any previous PRs, but it will be great if PR #3 is already merged before this. @sjanssen2

### CODE REVIEW

**Comment by qiyunzhu** [comment]
@sjanssen2 Would you like to check out the full manual and the example files? Thanks!

**Comment by sjanssen2** [comment]
This PR seems to contain more than just example input files. Why?

**Comment by qiyunzhu** [comment]
@sjanssen2 This PR is dependent on the last PR, which was just merged (thanks to @antgonza !). Now there is no code update left.

**Comment by mortonjt** [comment]
Looking at the html, there appears to be some words cut off.  Was this intentional?

**Comment by qiyunzhu** [comment]
@mortonjt Thanks for looking at it! Do you mean this? I intentionally made this in order to best mimic the Excel interface :)
screen shot 2016-11-01 at 2 56 17 pm

**Review by mortonjt — APPROVED** [review]

**Comment by mortonjt** [comment]
@antgonza want to merge?

**Comment by mortonjt** [comment]
Thanks @qiyunzhu !

**Comment by qiyunzhu** [comment]
Thanks @mortonjt @sjanssen2 !

**Pull request merged**
