### PR TITLE
added manual for plate_mapper

### PR DESCRIPTION
**Pull request by qiyunzhu**
I created a user's guide for plate_mapper. It is in static HTML format (because GitHub markdown lacks certain formatting function). Please download this file and view in a browser. So far I defined the input file format standards. This is based on conversations between me and Greg. I tried to be as compatible as possible with the wet lab's convention. The spreadsheet may not sound like a computationally efficient format, but that's what the wet lab are used to dealing with.

### CODE REVIEW

**Comment by mortonjt** [comment]
I think this looks good. But it looks like a `plate_mapper` module needs to be defined first.  Want to push that in first before merging this in?  Just in case there are changes to the readme.

**Comment by qiyunzhu** [comment]
@mortonjt Thanks! By module do you mean the actual Python code? It is in progress now. In the manual I defined the question we are going to solve, then I wrote a script to solve this question. Does that sound logic?

**Comment by mortonjt** [comment]
👍 so let's wait to merge this.

**Comment by sjanssen2** [comment]
As far as I understand this PR it is only about the concept (i.e. the description in the HTML file). By merging this, we would give @qiyunzhu the go to code something. So why and for what should we wait here @mortonjt ?

**Pull request merged**
